<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsE1xbq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsE1xbq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBsE1xbq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBsE1xbq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBsE1xbq\App_KernelDevDebugContainer([
    'container.build_hash' => 'BsE1xbq',
    'container.build_id' => '79601dc1',
    'container.build_time' => 1582542978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsE1xbq');
