<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container33ExD8h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container33ExD8h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container33ExD8h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container33ExD8h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container33ExD8h\App_KernelDevDebugContainer([
    'container.build_hash' => '33ExD8h',
    'container.build_id' => '561685b3',
    'container.build_time' => 1582538727,
], __DIR__.\DIRECTORY_SEPARATOR.'Container33ExD8h');
