<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8MBSsIs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8MBSsIs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8MBSsIs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8MBSsIs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8MBSsIs\App_KernelDevDebugContainer([
    'container.build_hash' => '8MBSsIs',
    'container.build_id' => '78d51df8',
    'container.build_time' => 1583174968,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8MBSsIs');
